import "unknwn.idl";
[object, uuid(0FFBDAAD-FCA7-11D2-8FF4-00105AA45BDC)]
interface ITest : IUnknown
{
	HRESULT GetText([out, string] wchar_t **pszMessage);
}
cpp_quote("DEFINE_GUID(CLSID_Test, 0xffbdaac, 0xfca7, 0x11d2, 0x8f, 0xf4, 0x0, 0x10, 0x8, 0x5, 0x5b, 0xDC);")
cpp_quote("DEFINE_GUID(IID_ITest,0xffbdaad, 0xfca7, 0x11d2, 0x8f, 0xf4, 0x0, 0x10, 0x5a, 0xa4, 0x5b, 0xDC);")
cpp_quote("DEFINE_GUID(APPID_Test,0xffbdaae, 0xfca7, 0x11d2, 0x8f, 0xf4, 0x0, 0x10, 0x5a, 0xa4, 0x5b, 0xDC);")
